# Generated by Django 5.2.14 on 2026-05-27 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('latin_name', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('light', models.CharField(choices=[('low', 'Тень'), ('medium', 'Рассеянный свет'), ('high', 'Яркий свет')], default='medium', max_length=20)),
                ('humidity', models.PositiveSmallIntegerField(default=50)),
                ('watering_interval_days', models.PositiveSmallIntegerField(default=7)),
                ('pet_safe', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'вид растения',
                'verbose_name_plural': 'виды растений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'коллекция',
                'verbose_name_plural': 'коллекции',
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CollectionPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantcare.collection')),
            ],
            options={
                'verbose_name': 'растение в коллекции',
                'verbose_name_plural': 'растения в коллекциях',
            },
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=120)),
                ('location_type', models.CharField(choices=[('indoor', 'В помещении'), ('balcony', 'На балконе')], default='indoor', max_length=20)),
                ('planted_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('watering_interval_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_watered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collections', models.ManyToManyField(related_name='plants', through='plantcare.CollectionPlant', to='plantcare.collection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_plants', to='plantcare.plantspecies')),
            ],
            options={
                'verbose_name': 'растение пользователя',
                'verbose_name_plural': 'растения пользователя',
                'ordering': ['nickname'],
                'unique_together': {('owner', 'nickname')},
            },
        ),
        migrations.AddField(
            model_name='collectionplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantcare.userplant'),
        ),
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('water', 'Полив'), ('fertilize', 'Удобрение'), ('repot', 'Пересадка'), ('prune', 'Обрезка')], default='water', max_length=20)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Выполнено'), ('skipped', 'Пропущено')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plantcare.userplant')),
            ],
            options={
                'verbose_name': 'задача ухода',
                'verbose_name_plural': 'задачи ухода',
                'ordering': ['due_date', 'plant__nickname'],
            },
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('water', 'Полив'), ('fertilize', 'Удобрение'), ('repot', 'Пересадка'), ('prune', 'Обрезка')], default='water', max_length=20)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='plantcare.userplant')),
            ],
            options={
                'verbose_name': 'запись ухода',
                'verbose_name_plural': 'записи ухода',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='collectionplant',
            unique_together={('collection', 'plant')},
        ),
    ]
